const { DataTypes } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const Attendance = sequelize.define('Attendance', {
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        employeeId: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'employees',
                key: 'id',
            },
            onDelete: 'CASCADE',
        },
        shiftAssignmentId: {
            type: DataTypes.INTEGER,
            allowNull: true,
            references: {
                model: 'shift_assignments',
                key: 'id',
            },
            onDelete: 'SET NULL',
        },
        shiftTypeId: {
            type: DataTypes.INTEGER,
            allowNull: true,
            references: {
                model: 'shift_types',
                key: 'id',
            },
            onDelete: 'SET NULL',
        },
        attendanceDate: {
            type: DataTypes.DATEONLY,
            allowNull: false,
            comment: 'Date of attendance',
        },
        scheduledStartTime: {
            type: DataTypes.TIME,
            allowNull: true,
            comment: 'Scheduled shift start time',
        },
        scheduledEndTime: {
            type: DataTypes.TIME,
            allowNull: true,
            comment: 'Scheduled shift end time',
        },
        firstCheckIn: {
            type: DataTypes.DATE,
            allowNull: true,
            comment: 'First check-in timestamp',
        },
        lastCheckOut: {
            type: DataTypes.DATE,
            allowNull: true,
            comment: 'Last check-out timestamp',
        },
        totalCheckIns: {
            type: DataTypes.INTEGER,
            allowNull: false,
            defaultValue: 0,
            comment: 'Total number of check-ins',
        },
        totalCheckOuts: {
            type: DataTypes.INTEGER,
            allowNull: false,
            defaultValue: 0,
            comment: 'Total number of check-outs',
        },
        workingHours: {
            type: DataTypes.DECIMAL(5, 2),
            allowNull: true,
            comment: 'Total working hours calculated',
        },
        breakHours: {
            type: DataTypes.DECIMAL(5, 2),
            allowNull: true,
            defaultValue: 0.00,
            comment: 'Total break hours',
        },
        overtimeHours: {
            type: DataTypes.DECIMAL(5, 2),
            allowNull: true,
            defaultValue: 0.00,
            comment: 'Overtime hours worked',
        },
        status: {
            type: DataTypes.ENUM('Present', 'Absent', 'Half Day', 'Late', 'Leave', 'Holiday', 'Week Off'),
            allowNull: false,
            defaultValue: 'Present',
            comment: 'Attendance status',
        },
        isLate: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: false,
            comment: 'Whether employee was late',
        },
        lateByMinutes: {
            type: DataTypes.INTEGER,
            allowNull: true,
            defaultValue: 0,
            comment: 'Minutes late after grace period',
        },
        isEarlyExit: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: false,
            comment: 'Whether employee left early',
        },
        earlyExitMinutes: {
            type: DataTypes.INTEGER,
            allowNull: true,
            defaultValue: 0,
            comment: 'Minutes of early exit',
        },
        isHoliday: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: false,
            comment: 'Whether this day is a holiday',
        },
        isWeekOff: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: false,
            comment: 'Whether this day is a week off',
        },
        autoGenerated: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: false,
            comment: 'Whether attendance was auto-generated',
        },
        remarks: {
            type: DataTypes.TEXT,
            allowNull: true,
            comment: 'Additional remarks or notes',
        },
        companyId: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'companies',
                key: 'id',
            },
            onDelete: 'CASCADE',
        },
        approvedBy: {
            type: DataTypes.INTEGER,
            allowNull: true,
            references: {
                model: 'users',
                key: 'id',
            },
            onDelete: 'SET NULL',
        },
        approvedAt: {
            type: DataTypes.DATE,
            allowNull: true,
        },
        createdBy: {
            type: DataTypes.INTEGER,
            allowNull: true,
            references: {
                model: 'users',
                key: 'id',
            },
            onDelete: 'SET NULL',
        },
        updatedBy: {
            type: DataTypes.INTEGER,
            allowNull: true,
            references: {
                model: 'users',
                key: 'id',
            },
            onDelete: 'SET NULL',
        },
    }, {
        tableName: 'attendance',
        timestamps: true,
        indexes: [
            {
                unique: true,
                fields: ['employeeId', 'attendanceDate'],
                name: 'unique_employee_attendance_date'
            },
            {
                fields: ['companyId', 'attendanceDate'],
                name: 'company_attendance_date_index'
            },
            {
                fields: ['status'],
                name: 'attendance_status_index'
            },
            {
                fields: ['shiftTypeId'],
                name: 'shift_type_attendance_index'
            },
        ],
    });

    // Force sync to update table structure (only in development)
    if (process.env.NODE_ENV === 'development') {
        Attendance.sync({ alter: true }).then(() => {
            console.log('Attendance table synced successfully');
        }).catch(err => {
            console.error('Error syncing Attendance table:', err);
        });
    }

    return Attendance;
};
